version: '3'
services:
    redis:
      image: 'redis'
      restart: always
      ports:
        - '6379:6379'
      volumes:
        - ./db-data/redis:/data
    postgres:
      image: 'postgres:14.0'
      restart: always
      ports:
        - '5432:5432'
      deploy:
        mode: replicated
        replicas: 1
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123456789
        POSTGRES_DB: auth
      volumes:
        - ./db-data/postgres/:/var/lib/postgresql/data/