# Generated by Django 4.2.13 on 2024-05-25 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assets",
            fields=[
                (
                    "assets_id",
                    models.IntegerField(default=0, primary_key=True, serialize=False),
                ),
                ("assets_name", models.CharField(max_length=100)),
                ("assets_type", models.CharField(max_length=100)),
                ("assets_url", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "country_code",
                    models.CharField(
                        default="VIE", max_length=5, primary_key=True, serialize=False
                    ),
                ),
                ("country_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Pack",
            fields=[
                (
                    "pack_name",
                    models.CharField(
                        default=None, max_length=100, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "role_id",
                    models.IntegerField(default=0, primary_key=True, serialize=False),
                ),
                ("role_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.CharField(
                        default=None, max_length=100, primary_key=True, serialize=False
                    ),
                ),
                ("password", models.CharField(max_length=100)),
                (
                    "email",
                    models.CharField(default="none@gm.uit.edu.vn", max_length=100),
                ),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.IntegerField(
                        choices=[(1, "Male"), (2, "Female"), (3, "Other")]
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        default="VIE",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="culturista_web.country",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="culturista_web.role",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "room_id",
                    models.IntegerField(default=0, primary_key=True, serialize=False),
                ),
                ("is_full", models.BooleanField()),
                (
                    "round1_pack",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round1_packs",
                        to="culturista_web.pack",
                    ),
                ),
                (
                    "round2_pack",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round2_packs",
                        to="culturista_web.pack",
                    ),
                ),
                (
                    "round3_pack",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round3_packs",
                        to="culturista_web.pack",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "question_id",
                    models.IntegerField(default=0, primary_key=True, serialize=False),
                ),
                ("question_type", models.CharField(max_length=100)),
                ("question_content", models.CharField(max_length=255)),
                ("answer", models.CharField(max_length=255)),
                ("score_value", models.FloatField()),
                (
                    "pack_name",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="culturista_web.pack",
                    ),
                ),
                (
                    "question_material",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="culturista_web.assets",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Forum",
            fields=[
                (
                    "content_id",
                    models.IntegerField(default=0, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("tag", models.CharField(max_length=100)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user_created_name",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="culturista_web.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "comment_id",
                    models.IntegerField(default=0, primary_key=True, serialize=False),
                ),
                ("comment_content", models.TextField()),
                (
                    "content_id",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="culturista_web.forum",
                    ),
                ),
                (
                    "user_name",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="culturista_web.user",
                    ),
                ),
            ],
        ),
    ]
